### ISSUE TITLE
Crux migration to Maven Central

### ISSUE THREAD

**Issue by jarohen** [teknql/crux-geo#1]
Hey @rschmukler - guess you may have seen this on the Clojurians Slack but thought I'd raise an issue here just in case.

A quick heads up that we're looking to migrate Crux over to Maven Central shortly - we've got a couple of non-Clojure modules coming soon, and would generally like to make Crux more accessible/appealing to folks outside of the Clojure community too. We've mirrored our Clojars dependencies onto Central, and have re-released 1.17.1 (currently as `1.17.1-rc1`) so that users can migrate without having to upgrade Crux.

Crux PRs here:
* https://github.com/juxt/crux/pull/1543
* https://github.com/juxt/crux/pull/1550

Could you let us know if this will cause you any issues, or whether there's anything we should do/avoid doing? Otherwise, if this works for you, I'm happy to raise a quick PR with the required changes.

Cheers,

James

**Comment by rschmukler** [comment]
Hey @jarohen thanks for the heads up! I don't believe it'll cause any issues for us. Happy to accept the PRs or make the required changes whenever. Thanks again!
