### ISSUE TITLE
Current status or alternatives

### ISSUE THREAD

**Issue by nikonikoniko** [teknql/crux-geo#5]
Given that the library references `crux` instead of `xtdb`, it would be great to be able to find a status of the library somewhere, to know if it a current viable option for use.  

(Thanks!)

**Comment by rschmukler** [comment]
Heya! Sorry on the delay. 

My answer will likely be somewhat disappointing. I ended up running into issues with performantly merging large collections of results returned by the geospatial side of things. At the time xtdb had limitations in its APIs that didn't allow for lazy merging of query results meaning that if something returned 100,000 results (even if they would be filtered later) it would have to be deserialized from the DB all at once regardless.

Around the same time of realizing this performance limitation the crux -> xtdb rename happened and I didn't have a project for which the technology was a viable fit so the library basically was put on the back-burner.

I am hoping that Xtdb 2 might have some answers (providing they keep APIs for adding additional indices) but we will have to see.

As for alternatives, I don't have a great answer. Like I said, for my use-case (using Crux w/ ~2 million geospatial entities) the performance ended up being to slow. I ended up switching to PostGIS and giving up on having Datalog (fortunately the document versioning wasn't needed either).

Like I said, I'm sorry for the probably disappointing answer. If anyone is interested in bringing it up to speed w/ the XTDB APIs (or attempting to tune performance for large query result sets) I am happy to accept PRs; but I am not actively working on it.
